### ISSUE TITLE
error building from a fresh install of NPM and Bower packages

### ISSUE THREAD

**Issue by drewda** [transitland/feed-registry#390]
```sh
➜  feed-registry git:(master) ✗ ./node_modules/ember-cli/bin/ember serve
DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super(), addon: `ember-cli-font-awesome`
    at Function.addonProto._requireBuildPackages.transpileModules.pickFiles.initializeAddons.eachAddonInvoke._eachProjectAddonInvoke.args.cacheKeyForTree._fileSystemInfo.Addon.lookup (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/lib/models/addon.js:1610:27)
Cannot read property 'nodeModulesPath' of undefined
TypeError: Cannot read property 'nodeModulesPath' of undefined
    at DependencyVersionChecker.NPMDependencyVersionChecker (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)
    at VersionChecker.for (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli-version-checker/src/version-checker.js:17:12)
    at Class.module.exports.init (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli-babel/index.js:17:26)
    at Class.superWrapper [as init] (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.CoreObject (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/node_modules/core-object/core-object.js:9:15)
    at Class (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at Class (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/node_modules/core-object/core-object.js:21:5)
    at /Users/drew/code/transitland/feed-registry/node_modules/ember-cli/lib/models/addons-factory.js:55:21
    at visit (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/drew/code/transitland/feed-registry/node_modules/ember-cli/lib/utilities/DAG.js:138:9)
```

Appears to be related to `ember-cli-font-awesome` dependency.

Related:
- https://github.com/martndemus/ember-font-awesome/issues/113
- https://github.com/ember-cli/ember-cli/issues/5973

**Comment by drewda** [comment]
Just a side effect of using some new dependencies on my local copy. Not a problem with `package.json` in current master.
